---
- name: Install Angular-cli ( *** warning  ! If it lasts more than 2 minutes! Stop the process and restart the install.sh script ***  )
  npm:
    name: '@angular/cli'
    global: yes

- name: Instal ncu
  npm:
    name: npm-check-updates
    global: yes


