---
  - name: Include global_vars
    include_vars:
      file: 'defaults/main.yml'
      name:  global_vars

  - debug:
      msg: "Home path {{ global_vars.home_path }}"

  - name: Check if java is installed
    command: java -version
    become_user: '{{ global_vars.user_session }}'
    register: java_result
    ignore_errors: True

  - debug:
      var: java_result

  - debug:
      msg: "Failed - Java is not installed"
    when: java_result is failed

  - debug:
      msg: "Success - Java is installed"
    when:  java_result is success

  - import_tasks: tasks/java_install.yml
    when:  java_result is failed

  - debug:
      msg: "Proxy is activated? {{ global_vars.enable_proxy }}"

  - import_tasks: tasks/certificates.yml
    when: global_vars.enable_proxy

