---
  - name: Ensure http-proxy.conf existe
    file:
      state: touch
      path: "/etc/systemd/system/docker.service.d/http-proxy.conf"
    become : yes

  - name: configure environment proxys
    blockinfile:
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
        insertafter: EOF
        block: |
            [Service]
            ExecStart=/usr/bin/dockerd --dns 131.102.100.110 --dns 131.102.37.142 --dns 8.8.8.8 --dns 8.8.4.4 -H fd://

